backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Jumbotron"
        name: "home-jumbotron"
        file: "content/home/jumbotron.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "ButtonText", name: "Button", widget: "string" }
          - { label: "Url", name: "link", widget: "string" }
          - { label: "Background image", name: "bg_image", widget: "image" }
      - label: "Favorites"
        name: "home-favorites"
        file: "content/home/favorites.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Favorite Furniture",
              name: "favorit_furniture",
              widget: "relation",
              collection: "furniture",
              multiple: true,
              search_fields: ["title"],
              value_field: "{{slug}}",
              display_fields: ["title"],
            }
  - label: "Furniture"
    name: "furniture"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    folder: "content/furniture"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["chair", "table"],
        }
