backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Croatina"
        name: "hr"
        file: "content/hr/home.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Link text", name: "link_text", widget: "string" }
          - { label: "Link url", name: "link_url", widget: "string" }
          - { label: "Background image", name: "bg_image", widget: "image" }
      - label: "English"
        name: "en"
        file: "content/en/home.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Link text", name: "link_text", widget: "string" }
          - { label: "Link url", name: "link_url", widget: "string" }
          - { label: "Background image", name: "bg_image", widget: "image" }
      - label: "German"
        name: "de"
        file: "content/de/home.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Link text", name: "link_text", widget: "string" }
          - { label: "Link url", name: "link_url", widget: "string" }
          - { label: "Background image", name: "bg_image", widget: "image" }
      - label: "Russian"
        name: "ru"
        file: "content/ru/home.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Link text", name: "link_text", widget: "string" }
          - { label: "Link url", name: "link_url", widget: "string" }
          - { label: "Background image", name: "bg_image", widget: "image" }
  - label: "Furniture Croatian"
    name: "furniture_hr"
    folder: "content/hr/furniture"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["chair", "table"],
        }
      - {
          label: "Type of mechanism",
          name: "mechanism",
          widget: "select",
          options: ["mechanically", "semi-mechanical", "automatic"],
          required: false,
        }
      - { label: "Width", name: "width", widget: "string" }
      - { label: "Height", name: "height", widget: "string" }
      - { label: "Lenght", name: "lenght", widget: "string" }
      - { label: "Material", name: "material", widget: "string" }
  - label: "Furniture English"
    name: "furniture_en"
    folder: "content/en/furniture"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["chair", "table"],
        }
      - {
          label: "Type of mechanism",
          name: "mechanism",
          widget: "select",
          options: ["mechanically", "semi-mechanical", "automatic"],
          required: false,
        }
      - { label: "Width", name: "width", widget: "string" }
      - { label: "Height", name: "height", widget: "string" }
      - { label: "Lenght", name: "lenght", widget: "string" }
      - { label: "Material", name: "material", widget: "string" }
  - label: "Furniture German"
    name: "furniture_de"
    folder: "content/de/furniture"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["chair", "table"],
        }
      - {
          label: "Type of mechanism",
          name: "mechanism",
          widget: "select",
          options: ["mechanically", "semi-mechanical", "automatic"],
          required: false,
        }
      - { label: "Width", name: "width", widget: "string" }
      - { label: "Height", name: "height", widget: "string" }
      - { label: "Lenght", name: "lenght", widget: "string" }
      - { label: "Material", name: "material", widget: "string" }
  - label: "Furniture Russian"
    name: "furniture_ru"
    folder: "content/ru/furniture"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["chair", "table"],
        }
      - {
          label: "Type of mechanism",
          name: "mechanism",
          widget: "select",
          options: ["mechanically", "semi-mechanical", "automatic"],
          required: false,
        }
      - { label: "Width", name: "width", widget: "string" }
      - { label: "Height", name: "height", widget: "string" }
      - { label: "Lenght", name: "lenght", widget: "string" }
      - { label: "Material", name: "material", widget: "string" }
